name: deploy

on:
  pull_request:
    branches:
      - prod
    types: [closed]

#on:
#  push:
#    branches:
#      - dev-*

jobs:
  unittest:
    name: unittest
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      # See: https://github.com/actions/setup-python
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # install pipenv and deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      # test
      - name: Run Tests
        run: python run_unittest.py

  deploy:
    name: deploy
    needs: unittest
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      # install severlessfreamework
      - name: Install severlessfreamework
        run: npm i
      # Deploy to Lambda
      - name: Deploy to Lambda
        run: npx sls deploy -v --stage=prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
